// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          int32            `json:"id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	Status      pgtype.Text      `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
